// src/components/Footer.vue
<script setup lang="ts">
import { Mail, Phone, Instagram } from 'lucide-vue-next'
import logoUns from '@/assets/logo_uns.webp'
import logoPtik from '@/assets/logo_ptik.webp'
</script>

<template>
  <footer class="w-full bg-[#f2f3ff] border-t border-[#005ea4]/10 rounded-t-[40px] px-6 py-12 md:py-16 md:px-12 mt-20 font-meiland">
    <div class="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-8 md:gap-12">
      
      <!-- Brand & Mission (6 columns on desktop) -->
      <div class="col-span-1 md:col-span-6 flex flex-col gap-4">
        <h3 class="font-rexlia text-xl tracking-wider text-brand-navy">
          BYTESFEST <span class="text-brand-blue-light font-bold">2026</span>
        </h3>
        <p class="text-brand-grey text-sm md:text-base max-w-md leading-relaxed">
          Program tahunan berskala nasional oleh HMP MIKROPTIK UNS. Wadah bagi pelajar, mahasiswa, dan masyarakat untuk menerapkan pengetahuan dan keterampilan teknologi dalam suasana kreatif, kolaboratif, dan kompetitif.
        </p>
      </div>

      <!-- Social Media Links (3 columns on desktop) -->
      <div class="col-span-1 md:col-span-3 flex flex-col gap-4">
        <h4 class="font-rexlia text-sm tracking-widest text-brand-navy uppercase">
          Media Sosial
        </h4>
        <div class="flex items-center gap-3">
          <a 
            href="https://instagram.com/bytesfest" 
            target="_blank" 
            rel="noopener noreferrer"
            class="w-11 h-11 rounded-full border border-brand-blue/20 bg-white flex items-center justify-center text-brand-navy hover:bg-brand-blue hover:text-white hover:border-brand-blue hover:-translate-y-1 transition-all duration-300 shadow-sm"
          >
            <Instagram class="w-5 h-5" />
          </a>
          <a 
            href="https://tiktok.com/@bytesfest" 
            target="_blank" 
            rel="noopener noreferrer"
            class="w-11 h-11 rounded-full border border-brand-blue/20 bg-white flex items-center justify-center text-brand-navy hover:bg-brand-blue hover:text-white hover:border-brand-blue hover:-translate-y-1 transition-all duration-300 shadow-sm"
          >
            <svg class="w-5 h-5" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1-.1z"/>
            </svg>
          </a>
        </div>
      </div>

      <!-- Contact Info (3 columns on desktop) -->
      <div class="col-span-1 md:col-span-3 flex flex-col gap-4">
        <h4 class="font-rexlia text-sm tracking-widest text-brand-navy uppercase">
          Hubungi Kami
        </h4>
        <ul class="flex flex-col gap-3 text-sm text-brand-grey">
          <li class="flex items-center gap-3">
            <div class="w-8 h-8 rounded-lg bg-white border border-brand-blue/10 flex items-center justify-center text-brand-blue">
              <Mail class="w-4 h-4" />
            </div>
            <a href="mailto:bytesfesthmpmikroptik@gmail.com" class="hover:text-brand-blue transition-colors duration-300">
              bytesfesthmpmikroptik@gmail.com
            </a>
          </li>
          <li class="flex items-center gap-3">
            <div class="w-8 h-8 rounded-lg bg-white border border-brand-blue/10 flex items-center justify-center text-brand-blue">
              <Phone class="w-4 h-4" />
            </div>
            <a href="https://wa.me/6282223533028" class="hover:text-brand-blue transition-colors duration-300">
              +62 822-2353-3028
            </a>
          </li>
        </ul>
      </div>

    </div>

    <!-- Bottom Copyright -->
    <div class="max-w-6xl mx-auto mt-12 pt-6 border-t border-brand-blue/10 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-brand-grey/70">
      <div class="flex items-center gap-4">
        <img :src="logoUns" alt="UNS Logo" class="h-10 w-auto object-contain" />
        <img :src="logoPtik" alt="PTIK Logo" class="h-10 w-auto object-contain" />
      </div>
      <p>&copy; 2026 BYTESFEST. All rights reserved.</p>
    </div>
  </footer>
</template>

// src/components/Footer.svelte
<footer class="bg-neutral-950 bg-gradient-to-b to-sky-500">
  <div class="container mx-auto w-full">
    <div class="grid w-full grid-flow-col grid-cols-1 grid-rows-3 lg:grid-cols-12 lg:grid-rows-1 lg:gap-4">
      <div class="my-6 mt-4 lg:col-span-3 lg:mb-0">
        <img class="mx-auto h-36 max-w-full object-cover lg:h-64" src="/img/Mascot Pose 1.png" alt="Mascot Pose">
      </div>
      <div class="mt-4 text-center lg:col-span-6 lg:mt-10">
        <div class="flex-col">
          <div class="mb-5 text-2xl lg:text-3xl">
            <h1 class="text-shadow-hero-md font-semibold tracking-wider text-neutral-0">
              Bytes<span class="bg-gradient-to-r from-blue-500 to-cyan-300 bg-clip-text text-transparent">fest</span>
              <span class="bg-gradient-to-r from-blue-500 to-cyan-300 bg-clip-text text-transparent">2025</span>
            </h1>
          </div>
          <div class="mb-5 text-blue-200">
            <span> Bunch of Youth Technottraction and Sport Festival </span>
          </div>
          <div class="mb-5 text-xs text-neutral-50 md:text-sm">
            <span> © Copyright 2025 - Bytesfest 2025 </span>
          </div>
        </div>
      </div>
      <div class="lg:col-span-3 lg:mt-16 lg:text-center">
        <div class="flex-col items-center text-center lg:text-center">
          <div class="text-md mt-2 font-light">
            <h2 class="mb-5 text-base md:text-lg">Contact Person</h2>
          </div>
          <div class="flex justify-center gap-6">
            <a href="mailto:bytesfesthmpmikroptik@gmail.com" target="_blank" rel="noreferrer" class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-100">
              <img class="h-8 w-8 icon" src="/img/Desain tanpa judul (11).png" alt="">
            </a>
            <a href="https://www.instagram.com/bytesfest" target="_blank" rel="noreferrer" class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-100">
              <img class="h-7 w-7 icon" src="/img/icon-instagram.png" alt="">
            </a>
            <a href="https://www.tiktok.com/@bytesfest" target="_blank" rel="noreferrer" class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-100">
              <img class="h-7 w-7 icon" src="/img/icon-tik-tok.png" alt="">
            </a>
            <a href="https://wa.me/6282223533028" target="_blank" rel="noreferrer" class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-100">
              <img class="h-7 w-7 icon" src="/img/icon-whatsapp.png" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
